config/routes.rb
MiniFacebook::Application.routes.draw do

  get "facebook/get_messages"
  get "facebook/home"
  get "facebook/profile"
  get "facebook/find_friends"
  get "facebook/log_out"
  get "facebook/friend_profile"
  delete "facebook/delete_post"
  delete "facebook/delete_notif"
  post "facebook/create_event"
  delete "facebook/delete_event"
  post "facebook/add_friend"
  post "facebook/send_message"
  post "facebook/send_request"
  post "facebook/deny_request"
  post "facebook/post_text"
  post "facebook/like_post"
  post "facebook/dislike_post"
  post "facebook/add_comment"
  post "facebook/save_settings"
  post "facebook/share_post"
  delete "facebook/delete_comment"

  patch "profile/update_basic"
  patch "profile/update_contact"
  post "profile/add_contact"
  patch "profile/update_job"
  post "profile/add_job"
  patch "profile/update_education"
  post "profile/add_education"
  post "profile/upload_photo"
  delete "profile/delete_friend"

  get "login/new"
  post "login/login_try"
  post "login/create"
  get "login/index"

  root 'login#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :mail, presence: true, uniqueness: true
  validates :name, :last_name, length: {minimum: 1}
  validates :birth, :gender, presence: true
  validates :password, length: {in: 6..20}

  has_many :messages, dependent: :destroy
  has_many :friends, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :events, dependent: :destroy

  has_one :settings, dependent: :destroy
  has_one :job, dependent: :destroy
  has_one :education, dependent: :destroy
  has_one :relationship, dependent: :destroy
  has_one :contact, dependent: :destroy

  # @param [Object] id
  def self.get_friends(id)
    @user = self.find(id)
    friends = Array.new
    if @user
      @user.friends.each do |f|
        friends << self.find(f.friend_id)
      end
    end
    return friends
  end

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE :src or last_name LIKE :src or mail LIKE :src', {:src => "%#{search}%"}])
    else
      find(:all)
    end
  end

end

app/controllers/facebook_controller.rb
class FacebookController < ApplicationController
  respond_to :html, :js
  before_filter :authenticate_user
  @@clicked_friend_id = nil # for messaging system, messages will be sent to selected user in inbox list

  def home
    if session[:user_id]
      @user = User.find(session[:user_id])
    else
      redirect_to login_index_path
    end
  end

  def delete_notif
    if params[:notif_id]
      @notif = Notification.find(params[:notif_id])
      @notif.destroy
    end
    render 'delete_notif.js'
  end

  def send_message
    f_id = @@clicked_friend_id
    u_id = session[:user_id]
    msg = params[:message]
    if f_id && msg
      @user = User.find(u_id)
      @friend = User.find(f_id)
      @message = Message.new(to_user_id: f_id, message: msg, user_id: u_id)
      @user.messages << @message
      @user.save
    end
    render 'send_message.js'
  end

  # Called when clicked a user in inbox panel at home page
  def get_messages
    f_id = params[:friend_id]
    @@clicked_friend_id = f_id
    u_id = session[:user_id]
    if f_id
      @user = User.find(u_id)
      @friend = User.find(f_id)
      @messages = Message.where("user_id = #{f_id} and to_user_id = #{u_id} or user_id = #{u_id} and to_user_id = #{f_id}").
          order(created_at: :desc).limit(50)
    end
    render 'show_message.js'
  end

  def friend_profile
    @user = User.find(session[:user_id])
    @friend = User.find(params[:friend_id])
  end

  def add_friend
    if params[:friend_id]
      @user = User.find(session[:user_id])
      friend = User.find(params[:friend_id])
      friend.friends.create(friend_id: @user.id)
      @user.friends.create(friend_id: params[:friend_id])
      @request = Request.find(params[:request_id])
      @request.destroy
    end
    render 'answer_request.js'
  end

  def deny_request
    if params[:request_id] #request id
      @request = Request.find(params[:request_id])
      @request.destroy
    end
    render 'answer_request.js'
  end

  def send_request
    if params[:id]
      @user = User.find(session[:user_id])
      @friend = User.find(params[:id])
      @friend.requests.create(from_user_id: @user.id)
    end
    render 'send_request.js'
  end

  def find_friends
    @user = User.find(session[:user_id])
    @friends = User.search(params[:src_term])

      @friends.select { |f| f.id == @user.id || (!f.settings.nil? && f.settings.src_hide == true) }.each do |d|
        @friends.delete(d)
      end

  end

  def profile
    if session[:user_id]
      @user = User.find(session[:user_id])
    else
      redirect_to login_index_path
    end
  end

  def post_text
    @user = User.find(session[:user_id])
    @is_home = params[:is_home] == "true"
    if @user
      @user.posts.create(post: params[:post])
      send_notif_to_friends @user, 0, params[:post]
    end
    render 'post_text.js'
  end

  def like_post
    if params[:post_id]
      @user = User.find(session[:user_id])
      @post = Post.find(params[:post_id])
      like true, @post
      send_notif_to_friends @user, 1, @post.post
    end
    render 'like_post.js'
  end

  def dislike_post
    if params[:post_id]
      @user = User.find(session[:user_id])
      @post = Post.find(params[:post_id])
      like false, @post
      send_notif_to_friends @user, 2, @post.post
    end
    render 'like_post.js'
  end

  def share_post
    p_id = params[:post_id]
    if p_id
      @user = User.find(session[:user_id])
      posts = @user.posts.select { |p| p.id == p_id }
      if posts.empty?
        text = Post.find(p_id).post
        @user.posts.create(post: text)
      end
    end
    render 'profile'
  end

  def add_comment
    p_id = params[:post_id]
    comment = params["comment_#{p_id}"]
    if p_id && comment
      @user = User.find(session[:user_id])
      @post = Post.find(p_id)
      @user.comments.create(post_id: p_id, text: comment)
      send_notif_to_friends @user, 3, comment
    end
    render 'add_comment.js'
  end

  def delete_comment
    if params[:comment_id]
      @comment = Comment.find(params[:comment_id])
      @comment.destroy
    end
    render 'delete_comment.js'
  end

  def delete_post
    if params[:post_id]
      @user = User.find(session[:user_id])
      @post = @user.posts.find(params[:post_id])
      @post.destroy
    end
    render 'delete_post.js'
  end

  def create_event
    @event = Event.new
    @event.name = params[:name]
    @event.details = params[:details]
    @event.when = params[:when]
    @event.begin_time = params[:begin_time]
    @event.until = params[:until]
    @event.end_time = params[:end_time]
    @user = User.find(session[:user_id])
    @user.events << @event
    @user.save
    send_notif_to_friends @user, 4, @event.name
    redirect_to facebook_home_path
  end

  def delete_event
    @event = Event.find(params[:event_id])
    @event.destroy
    render "delete_event.js"
  end

  def save_settings
    src_hid = params[:src_hide] == "true"
    user = User.find(session[:user_id])
    user.settings = Settings.new(src_hide: src_hid)
    user.save
    render :nothing => true
  end

  def log_out
    session[:user_id] = nil
    redirect_to login_index_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :last_name, :birth, :gender)
  end

  def send_notif_to_friends(user, type, content)
    # Send notification to all friends
    user.friends.each do |f|
      Notification.create(user_id: f.id, friend_id: user.id, content: content, notif_type: type)
    end
  end

  def like(is_like, post)
    if post # not null
      if is_like # like or dislike
        count = post.like # get like count
        if count # increment
          count += 1
        else # initialize
          count = 1
        end
        post.like = count # set like count
      else
        count = post.dislike # get dislikes
        if count # modify
          count -= 1
        else
          count = -1
        end
        post.dislike = count # set dislikes
      end
      post.save # save like or dislike count to db
    end
  end
end

app/helpers/facebook_helper.rb
module FacebookHelper
  def get_friends
    User.get_friends(session[:user_id])
  end

  # for comment partial view, to check whether a comment belongs to user or not
  def get_user_id
    session[:user_id]
  end

  def get_user(id)
    User.find(id)
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def create_notif_text(type)
    case type
      when 0
        "updated his status"
      when 1
        "like your post"
      when 3
        "commented on your post"
      when 4
        "created an event"
    end
  end

  def get_n_messages(user, num = 3)
    f_ids = Array.new
    user.friends.each do |f|
      f_ids << f.friend_id
    end
    Message.where("user_id in (?) and to_user_id = #{user.id} or user_id = #{user.id}", f_ids).
        order(created_at: :desc).limit(num)
  end

  # returns last message between user and friend
  def get_last_message(to_id, from_id)
    u_msg = User.find(to_id).messages.where(to_user_id: from_id).last
    f_msg = User.find(from_id).messages.where(to_user_id: to_id).last
    if f_msg != nil && u_msg != nil
      if f_msg.created_at > u_msg.created_at
        return f_msg
      else
        return u_msg
      end
    elsif f_msg == nil && u_msg != nil
      u_msg
    elsif u_msg == nil && f_msg != nil
      f_msg
    end
    nil
  end

  def get_home_posts
    user = User.find(session[:user_id])
    f_ids = Array.new
    f_ids << user.id
    @user.friends.each do |f|
      f_ids << f.friend_id
    end
    Post.where(user_id: f_ids).order(updated_at: :desc) # get posts using ids of friends
  end

  def is_friend(id)
    !User.find(session[:user_id]).friends.where(:friend_id => id).empty?
  end

  def is_request_sent(id)
    !User.find(id).requests.where(:from_user_id => session[:user_id]).empty?
  end

end

app/views/facebook/_footer.html.erb
<div class="clearfix"></div>

<hr>
<div class="col-md-12 text-center"><p>Copyright © 2014 Facelook. All right reserved.</p></div>
<hr>

app/views/facebook/_header.html.erb
<%= stylesheet_link_tag "facebook" %>

<div class="navbar navbar-fixed-top header">
  <div class="col-md-12">
    <!-- Facelook Header -->
    <div class="navbar-header">

      <!-- adding logo to the header -->
      <%= link_to image_tag("logo2.png", :border => 0, :alt => 'Facelook', :title => 'Logo', :size => '200x50'), facebook_home_path, :class => 'navbar-brand' %>

      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse1">
        <i class="glyphicon glyphicon-search"></i>
      </button>

    </div>
    <!-- Search and right buttons -->
    <div class="collapse navbar-collapse" id="navbar-collapse1">

      <!-- Search form-->
      <%= form_tag('find_friends', :class => 'navbar-form navbar-left', :method => 'get') do %>
          <div class="input-group" style="max-width:470px;margin-top: 10px">
            <%= text_field_tag :src_term, nil, :placeholder => "Search", :class => "form-control" %>
            <div class="input-group-btn">
              <%= button_tag :class => "btn btn-default btn-primary" do %>
                  <i class="glyphicon glyphicon-search"></i>
              <% end %>
            </div>
          </div>
      <% end %>

      <!-- Navigation buttons -->
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to ({:action => :profile}) do %>
              <i class="glyphicon glyphicon-user" style="color:#5cdd21;"></i> <%= user.name %>
          <% end %>
        </li>
        <li>
          <%= link_to ({:action => :home}) do %>
              <i class="glyphicon glyphicon-th-large" style="color:#0000aa;"></i> News Feed
          <% end %>
        </li>
        <li>
          <a href="#editSettingsModal" role="button" data-toggle="modal">
            <i class="glyphicon glyphicon-cog" style="color:#dd1111;"></i> Settings</a>
        </li>
        <li>
          <a href="#aboutModal" role="button" data-toggle="modal">
            <i class="glyphicon glyphicon-info-sign" style="color:#34a9dd;"></i> About</a>
        </li>
        <li>
          <%= link_to ({:action => :log_out}) do %>
              <i class="glyphicon glyphicon-log-out" style="color:#ddcc00;"></i> Log Out
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

<!-- ABOUT DIALOG -->
<div id="aboutModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="width:12px;">×</button>
        <h2 class="text-center">About</h2>
      </div>
      <h4 class="text-center">Developers</h4>
      <div class="modal-body">
        <div class="col-md-12 text-right">
          <p class="notice"><%= link_to image_tag("emre.jpg", :border => 0, :size => '75x75', :alt => '', :title => ''), "https://plus.google.com/+EmreArd%C4%B1%C3%A7/posts/hyZiG5wHpbX", :class => '' %> Emre Ardıç</p></br></br></br>
        </div>
        <div class="col-md-12 text-left">
          <p class="notice"><%= link_to image_tag("azat.jpg", :border => 0, :size => '75x75', :alt => '', :title => ''), "http://www.azatugurlu.com", :class => '' %>Azat Uğurlu</p>
      </div>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">OK</button>
      </div>
    </div>
  </div>
</div>

<!-- Settings DIALOG -->
<div id="editSettingsModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="width:12px;">×</button>
        <h2 class="text-center">Change Settings</h2>
      </div>
      <div class="modal-body">
        <div class="col-md-12">
          <%= form_tag(url_for(action: 'save_settings', controller: 'facebook'), :method => :post, :remote => true) do %>
              <table class="table">
                <tr>
                  <td><%= label_tag "Search" %></td>
                </tr>
                <tr>
                  <td><%= content_tag :p, "Hide profile in search?" %></td>
                  <td><%= check_box_tag :src_hide, true, false, :class => 'checkbox', :style => 'margin:auto' %></td>
                </tr>
              </table>
             <%= button_tag "Save", :class => 'btn' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/facebook/_right.html.erb
<div class="col-md-3 col-sm-6">
  <div class="panel panel-default">
    <div class="panel-heading">
      <a href="#requestModal" role="button" data-toggle="modal" class="pull-right">View all</a>
      <h4><i class="glyphicon glyphicon-retweet" style="color:#2262dd"></i>&nbsp;Requests</h4>
    </div>
    <div class="panel-body">
      <ul class="list-unstyled">
        <% if @user && !@user.requests.empty? %>
            <% @user.requests.reverse.take(3).each do |r| %>
                <% friend = get_user(r.from_user_id) %>
                <% if !friend.nil? %>
                    <li id="request_pre_id_<%= r.id %>" style="margin-top: 3px">
                      <div class="row clearfix">
                        <div class="col-sm-4 src-res-img">
                          <% if friend.img_id %>
                              <%= cl_image_tag friend.img_id, :width => 50, :height => 50, :class => 'center-block' %>
                          <% else %>
                              <%= image_tag('avatar.png', size: '50x50', class: 'center-block') %>
                          <% end %>
                        </div>
                        <div class="col-sm-6 src-res-group">
                          <p class="src-res-name"><%= "#{friend.name} #{friend.last_name}" %></p>
                        </div>
                      </div>
                    </li>
                <% end %>
            <% end %>
        <% else %>
            <p class="text-center text-info">No Requests</p>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <a href="#eventModal" role="button" data-toggle="modal" class="pull-right">Manage</a>
      <a href="#eventCreate" role="button" data-toggle="modal" class="pull-right">Create&nbsp;</a>
      <h4><i class="glyphicon glyphicon-star-empty" style="color:#2262dd"></i>&nbsp;Events</h4>
    </div>
    <div class="panel-body">
      <ul class="list-unstyled">
        <% if @user && !@user.events.empty? %>
            <% @user.events.take(3).each do |n| %>
                <li id="event_pre_id_<%= n.id %>" style="margin-top: 3px">
                  <div class="row clearfix">
                    <div class="col-sm-1 src-res-img" style="margin-right: 10px">
                      <i class="glyphicon glyphicon-calendar"></i>
                    </div>
                    <div class="col-md-10 src-res-group">
                      <span style="font-size: 15px"><%= n.name %></span>
                      <span style="font-size: 13px">&nbsp;<%= n.when %>&nbsp;</span>
                      <span class="text-overflow-hidden" style="font-size: 13px"><%= n.details %></span>
                    </div>
                  </div>
                </li>
            <% end %>
        <% else %>
            <p class="text-center text-info">No Events</p>
        <% end %>
      </ul>
    </div>
  </div>

</div>

<!-- REQUEST DIALOG -->
<div id="requestModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="width:12px;">×</button>
        <h2 class="text-center">Requests</h2>
      </div>
      <div class="modal-body">
        <ul class="list-unstyled">
          <% if @user && !@user.requests.empty? %>
              <% @user.requests.reverse.each do |r| %>
                  <li id="request_id_<%= r.id %>" style="margin-top: 3px">
                    <div class="row clearfix">
                      <% friend = get_user(r.from_user_id) %>
                      <div class="col-sm-2 src-res-img" style="margin-right: 5px">
                        <% if friend.img_id %>
                            <%= cl_image_tag friend.img_id, :width => 50, :height => 50, :class => 'center-block' %>
                        <% else %>
                            <%= image_tag('avatar.png', size: '50x50', class: 'center-block') %>
                        <% end %>
                      </div>
                      <div class="col-sm-4 src-res-group">
                        <p class="src-res-name"><%= "#{friend.name} #{friend.last_name}" %></p>
                        <p class="text-info src-res-info"><%= friend.mail %></p>
                      </div>
                      <div class="col-sm-4 pull-right" style="display: flex">
                        <%= button_to "Apply", {:action => 'add_friend', :friend_id => r.from_user_id, :request_id => r.id},
                                      :remote => true, :class => 'btn btn-default btn-sm' %>
                        <%= button_to "Deny", {:action => 'deny_request', :request_id => r.id}, :remote => true, :class => 'btn btn-default btn-sm',
                                      :style => 'margin-left:5px' %>
                      </div>
                    </div>
                  </li>
              <% end %>
          <% else %>
              <p class="text-center text-info">No Requests</p>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<!-- EVENTS DIALOG -->
<div id="eventModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="width:12px;">×</button>
        <h2 class="text-center">Events</h2>
      </div>
      <div class="modal-body">
        <ul class="list-unstyled">
          <% if @user && !@user.events.empty? %>
              <% @user.events.each do |n| %>
                  <li id="event_id_<%= n.id %>" style="margin-top: 3px">
                    <div class="row clearfix">
                      <div class="col-sm-1 src-res-img" style="margin-right: 10px">
                        <i class="glyphicon glyphicon-calendar"></i>
                      </div>
                      <div class="col-md-10 src-res-group">
                        <%= link_to "×", facebook_delete_event_path(:event_id => n.id), :remote => true, :class => 'close',
                                    :style => 'width:12px;margin:0px;font-size:16px;font-weight:normal', :method => 'delete' %>
                        <span style="font-size: 15px"><%= n.name %></span>
                        <span style="font-size: 13px">&nbsp;<%= n.when %>&nbsp;</span>
                        <span style="font-size: 13px"><%= n.details %></span>
                      </div>
                    </div>
                  </li>
              <% end %>
          <% else %>
              <p class="text-center text-info">No Events</p>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<!-- EVENTS DIALOG -->
<div id="eventCreate" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="width:12px;">×</button>
        <h2 class="text-center">Events</h2>
      </div>
      <div class="modal-body">
        <%= form_tag(url_for(action: 'create_event', controller: 'facebook'), :method => :post) do %>
            <p>
              <%= text_field_tag :name, nil, :placeholder => "Name", :class => 'form-control', :required => true %>
            </p>
            <p>
              <%= text_area_tag :details, nil, :placeholder => "Details", :class => 'form-control', :required => true %>
            </p>
            <p>
              <%= label_tag "When" %>
              <%= date_field_tag :when, nil, :class => 'form-control', :required => true %>
            </p>
            <p>
              <%= time_field_tag :begin_time, nil, :class => 'form-control' %>
            </p>
            <p>
              <%= label_tag "Until" %>
              <%= date_field_tag :until, nil, :class => 'form-control' %>
            </p>
            <p>
              <%= time_field_tag :end_time, nil, :class => 'form-control' %>
            </p>
            <%= button_tag "Create", :class => 'btn' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/facebook/_show_message.html.erb
<li style="margin-top: 3px">
  <div class="row clearfix" id="msg-reply-div">
    <div class="col-sm-2 src-res-img">
      <%# Profile picture of sender %>
      <% if friend.id == m.user_id %>
          <% if friend.img_id %> <%# Profile picture of friend %>
              <%= cl_image_tag friend.img_id, :width => 50, :height => 50, :class => 'center-block' %>
          <% else %>
              <%= image_tag('avatar.png', size: '50x50', class: 'center-block') %>
          <% end %>
      <% else %> <%# Profile picture of user %>
          <% if user.img_id %>
              <%= cl_image_tag user.img_id, :width => 50, :height => 50, :class => 'center-block' %>
          <% else %>
              <%= image_tag('avatar.png', size: '50x50', class: 'center-block') %>
          <% end %>
      <% end %>
    </div>
    <%# Name of user %>
    <div class="col-sm-10 src-res-group">
      <% if friend.id == m.user_id %>
          <%= link_to "#{friend.name} #{friend.last_name}", facebook_friend_profile_path(:friend_id => friend.id), :class => 'src-res-name' %>
      <% else %>
          <%= link_to "#{user.name} #{user.last_name}", facebook_profile_path, :class => 'src-res-name' %>
      <% end %>
      <br>
      <%# Profile picture of sender %>
      <p class="text-info src-res-info"><%= m.message %></p>
    </div>
  </div>
</li>

app/views/facebook/add_comment.js.erb
$("#comments_div_<%= @post.id %>").html("<%= j render(:partial => 'comment', :locals => { :post => @post }) %>");
$("#comment_<%= @post.id %>").val("");// Clear comment text input area

app/views/facebook/answer_request.js.erb
$("#request_id_<%= @request.id %>").fadeOut("slow", function () {
    $("#request_id_<%= @request.id %>").remove();
    $("#request_pre_id_<%= @request.id %>").remove();
});

app/views/facebook/delete_comment.js.erb
$("#comment_id_<%= @comment.id %>").fadeOut("slow", function () {
    $("#comment_id_<%= @comment.id %>").remove();
});

app/views/facebook/delete_post.js.erb
$("#post_div_<%= @post.id %>").fadeOut("slow", function () {
    $("#post_div_<%= @post.id %>").remove();
});

app/views/facebook/find_friends.html.erb
<!-- HEADER -->
<%= render partial: "header", locals: {user: @user} %>

<!-- HOME -->
<div class="container" id="main">

  <div class="row">

    <%= render partial: "left", locals: {user: @user} %>

    <!-- MIDDLE COLUMN -->
    <div class="col-md-6 col-sm-6">

      <%= render partial: "search", locals: {friends: @friends} %>

    </div>

    <%= render partial: "right", locals: {user: @user} %>

  </div>

</div>

app/views/facebook/friend_profile.html.erb
<!-- HEADER, Includes css,js libs  -->
<%= render partial: "header", locals: {user: @user} %>

<!-- HOME -->
<div class="container" id="main">

  <%= render partial: "profile", locals: {user: @friend, is_user: false} %>

</div>

app/views/facebook/home.html.erb
<!-- HEADER -->
<%= render partial: "header", locals: {user: @user} %>

<!-- HOME -->
<div class="container" id="main">

  <div class="row">

    <%= render partial: "left", locals: {user: @user} %>

    <!-- MIDDLE COLUMN -->
    <div class="col-md-6 col-sm-6">

      <%= render partial: "post_form", locals: {is_home: true} %>
      <!-- All post of user will be shown -->
      <div id="post_container">
        <%= render partial: "post", locals: {user: @user, is_home: true} %>
      </div>

    </div>

    <%= render partial: "right", locals: {user: @user} %>
    <!--FOOTER-->
    <%= render partial: "footer" %>

  </div>
</div>

app/views/facebook/like_post.js.erb
$("#like_<%= @post.id %>").html("<%= @post.like if @post.like != 0 %>");
$("#dislike_<%= @post.id %>").html("<%= @post.dislike if @post.dislike != 0 %>");

app/views/facebook/post_text.js.erb
$("#post_container").html("<%= j render(:partial => 'post', :locals => { :user => @user, :is_home => @is_home }) %>");
$("#post").val("");// Clear what do you think text box