config/routes.rb
MiniFacebook::Application.routes.draw do

  get "facebook/get_messages"
  get "facebook/home"
  get "facebook/profile"
  get "facebook/find_friends"
  get "facebook/log_out"
  get "facebook/friend_profile"
  delete "facebook/delete_post"
  delete "facebook/delete_notif"
  post "facebook/create_event"
  delete "facebook/delete_event"
  post "facebook/add_friend"
  post "facebook/send_message"
  post "facebook/send_request"
  post "facebook/deny_request"
  post "facebook/post_text"
  post "facebook/like_post"
  post "facebook/dislike_post"
  post "facebook/add_comment"
  post "facebook/save_settings"
  post "facebook/share_post"
  delete "facebook/delete_comment"

  patch "profile/update_basic"
  patch "profile/update_contact"
  post "profile/add_contact"
  patch "profile/update_job"
  post "profile/add_job"
  patch "profile/update_education"
  post "profile/add_education"
  post "profile/upload_photo"
  delete "profile/delete_friend"

  get "login/new"
  post "login/login_try"
  post "login/create"
  get "login/index"

  root 'login#index'

end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  before_filter :authenticate_user, :except => [:index, :create, :login_try, :new]
  before_filter :save_login_state, :only => [:new, :create, :index, :login_try]

  #Sing Up Form
  def new
    @user = User.new
  end

  # Registration method
  def create
    @user = User.new(user_params)
    if (@user.save)
      session[:user_id] = @user.id
      flash[:notice] = "Welcome, you logged in as #{@user.name}"
      redirect_to facebook_home_path
    else
      render "new"
    end
  end

  def login_try
    authorized_user = User.find_by(mail: params[:mail])
    if authorized_user && authorized_user.password == params[:password]
      session[:user_id] = authorized_user.id
      flash[:notice] = "Welcome, you logged in as #{authorized_user.name}"
      redirect_to facebook_home_path
    else
      flash[:notice] = "Invalid Username or Password"
      flash[:status]= "invalid"
      render "index"
    end
  end

  # Login Page
  def index
  end

  private
  def user_params
    params.require(:user).permit(:name, :last_name, :mail, :password, :birth, :gender)
  end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/login/index.html.erb
<%= stylesheet_link_tag "login" %>
<%= link_to image_tag("facelook_logo.png", :border => 0, :size => '300x75', :alt => '', :title => ''), facebook_home_path, :class => 'login_logo' %>

<h1>The Best Way to Socialize</h1>
<h2>Sign in to continue to Facelook</h2>
<div class="login">
  <%= image_tag("avatar.png", :size => "128x128", :class => "profile_image") %>
  <%= form_tag(:action => 'login_try') do %>
      <%= email_field_tag :mail, nil, :placeholder => "E Mail", :class => "input_field" %>
      <%= password_field_tag :password, nil, :placeholder => "Password", :class => "input_field" %>
      <%= button_tag "Login" %>
  <% end %>
  <% if flash[:status]== "invalid" %>
      <div class="invalid_notice">
        <p><%= flash[:notice] %></p>
      </div>
  <% end %>
</div>
<%= link_to "Register", login_new_path, :style => "color: blue" %>

app/views/login/new.html.erb
<%= stylesheet_link_tag "login" %>

<%= image_tag("facelook_logo.png", :border => 0, :size => '300x75', :class => 'login_logo') %>

<h1>Let's Get In</h1>
<div class="login register">
  <%= form_for(@user, :url => {:action => "create"}) do |f| %>
      <%= render partial: "layouts/errors", locals: {errors: @user.errors} %>
      <p>
        <%= f.text_field :name, :class => "input_field", :placeholder => "Name" %>
      </p>
      <p>
        <%= f.text_field :last_name, :class => "input_field", :placeholder => "Last Name" %>
      </p>
      <p>
        <%= f.email_field :mail, :class => "input_field", :placeholder => "Mail" %>
      </p>
      <p>
        <%= f.password_field :password, :class => "input_field", :placeholder => "Password" %>
      </p>
      <p>
        <%= f.label "Birthdate" %>
        <%= f.date_field :birth, :class => "input_field", :placeholder => "gg.aa.yyyy" %>
      </p>
      <p>
        <%= f.select :gender, options_for_select(['Male', 'Female']), {:prompt => 'Select Gender'}, :class => "select_field" %>
      </p>
      <p>
        <%= f.button "Register" %>
      </p>
  <% end %>
</div>
<%= link_to "Back to Login", login_index_path %>